import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'Introduction/intro',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 - The Foundation',
      collapsed: false,
      items: [
        'Module1-ROS2/introduction_to_ros2',
        'Module1-ROS2/ros2_fundamentals',
        'Module1-ROS2/introduction_to_ros2_further_details',
        'Module1-ROS2/ros2_fundamentals_detailed',
        'Module1-ROS2/robotics_basics',
        'Module1-ROS2/ros2_ecosystem_tools',
        'Module1-ROS2/nodes_topics_services',
        'Module1-ROS2/introduction_to_physical_ai',
        'Module1-ROS2/actions_parameters',
        'Module1-ROS2/introduction-to-ros2',
        'Module1-ROS2/ros2-nodes-topics-services',
        'Module1-ROS2/ros2-actions-advanced-communication',
        'Module1-ROS2/ros2-development-environment-tools',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation - Gazebo & Unity',
      collapsed: false,
      items: [
        'Module2-Simulation/Chapter1_Introduction_to_Simulation',
        'Module2-Simulation/Chapter2_Gazebo_Basics',
        'Module2-Simulation/Chapter3_Unity_for_Robotics',
        'Module2-Simulation/Chapter4_Additional_Simulation_Concepts',
        'Module2-Simulation/Chapter5_Gazebo_Advanced_Features',
        'Module2-Simulation/Chapter6_Unity_Advanced_Features',
        'Module2-Simulation/Chapter7_Simulation_Best_Practices',
        'Module2-Simulation/Chapter8_Introduction_to_Robot_Simulation',
        'Module2-Simulation/Chapter9_Gazebo_Basics',
        'Module2-Simulation/Chapter10_Unity_for_Robot_Visualization',
        'Module2-Simulation/Chapter11_Advanced_Simulation_Techniques',
        'Module2-Simulation/Chapter12_module2-gazebo-unity',
        'Module2-Simulation/Chapter13_module2-machine-learning',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac – Advanced Robotics',
      collapsed: false,
      items: [
        'Module3-NVIDIA-Isaac/Chapter1_Introduction_to_NVIDIA_Isaac',
        'Module3-NVIDIA-Isaac/Chapter2_Bipedal_Locomotion',
        'Module3-NVIDIA-Isaac/Chapter3_AI_Powered_Perception_and_Manipulation',
        'Module3-NVIDIA-Isaac/Chapter4_Sim_to_Real_Techniques',
        'Module3-NVIDIA-Isaac/Chapter5_Introduction_to_NVIDIA_Isaac',
        'Module3-NVIDIA-Isaac/Chapter6_Bipedal_Locomotion',
        'Module3-NVIDIA-Isaac/Chapter8_introduction_to_isaac',
        'Module3-NVIDIA-Isaac/Chapter9_isaac_sim',
        'Module3-NVIDIA-Isaac/Chapter10_isaac_ros',
        'Module3-NVIDIA-Isaac/Chapter11_isaac_navigation_manipulation',
        'Module3-NVIDIA-Isaac/Chapter12-introduction-to-nvidia-isaac',
        'Module3-NVIDIA-Isaac/Chapter13-isaac-sim-advanced-simulation',
        'Module3-NVIDIA-Isaac/Chapter14_module3-bipedal-locomotion',
        'Module3-NVIDIA-Isaac/Chapter15_module3-isaac',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Integration',
      collapsed: false,
      items: [
        'Module4-Vision-Language-Action/Chapter1_Introduction_to_VLA',
        'Module4-Vision-Language-Action/Chapter2_Voice_to_Action',
        'Module4-Vision-Language-Action/Chapter3_Language_Based_Cognitive_Planning',
        'Module4-Vision-Language-Action/Chapter4_Multimodal_Interaction_and_Control',
        'Module4-Vision-Language-Action/Chapter5_vla_overview',
        'Module4-Vision-Language-Action/Chapter6_vision_processing',
        'Module4-Vision-Language-Action/Chapter7_language_processing',
        'Module4-Vision-Language-Action/Chapter8_action_planning_execution',
        'Module4-Vision-Language-Action/Chapter9_module4-sensor-fusion',
        'Module4-Vision-Language-Action/Chapter10_module4-vla',
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      collapsed: false,
      items: [
        'Capstone-Project/capstone-design-challenge',
        'Capstone-Project/capstone_overview',
        'Capstone-Project/system_design',
      ],
    },
    {
      type: 'category',
      label: 'Hardware & Deployment Guide',
      collapsed: false,
      items: [
        'Hardware-Deployment/Chapter1_Hardware_Architecture',
        'Hardware-Deployment/Chapter2_Jetson_for_Robotics',
        'Hardware-Deployment/Chapter3_Sensor_Integration_and_Calibration',
        'Hardware-Deployment/Chapter4_Sim_to_Real_Deployment',
        'Hardware-Deployment/Chapter5_hardware_selection',
        'Hardware-Deployment/Chapter6_deployment_strategies',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      collapsed: false,
      items: [
        'Appendices/hardware-selection',
        'Appendices/deployment-guide',
        'Appendices/ros2_commands_reference',
        'Appendices/isaac_ros_reference',
        'Appendices/troubleshooting_guide',
        'Appendices/chapter-plan',
      ],
    },
  ],
};

export default sidebars;